aa3 = {"Ala": ["GCU", "GCC", "GCA", "GCG"],
       "Arg": ["CGU", "CGC", "CGA", "CGG", "AGA", "AGG"],
       "Asn": ["AAU", "AAC"],
       "Asp": ["GAU", "GAC"],
       "Cys": ["UGU", "UGC"],
       "Gln": ["CAA", "CAG"],
       "Glu": ["GAA", "GAG"],
       "Gly": ["GGU", "GGC", "GGA", "GGG"],
       "His": ["CAU", "CAC"],
       "Ile": ["AUU", "AUC", "AUA"],
       "Leu": ["UUA", "UUG", "CUU", "CUC", "CUA", "CUG"],
       "Lys": ["AAA", "AAG"],
       "Met": ["AUG"],
       "Phe": ["UUU", "UUC"],
       "Pro": ["CCU", "CCC", "CCA", "CCG"],
       "Ser": ["UCU", "UCC", "UCA", "UCG", "AGU", "AGC"],
       "Thr": ["ACU", "ACC", "ACA", "ACG"],
       "Trp": ["UGG"],
       "Tyr": ["UAU", "UAC"],
       "Val": ["GUU", "GUC", "GUA", "GUG"],
       "Start": ["AUG", "CUG", "UUG", "GUG", "AUU"],
       "Stop": ["UAG", "UGA", "UAA"]
       }

print(aa3["Leu"])
